name: Build and deploy - func-embedding-generator

on:
  push:
    branches:
      - main
    paths:
      - 'functions/func-embedding-generator/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions/func-embedding-generator'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Debug - List directory structure
        run: |
          echo "Current directory: $(pwd)"
          find . -type f -name "requirements.txt" | sort

      - name: Install dependencies
        run: |
          if [ -f "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt" ]; then
            pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt
          else
            echo "Requirements file not found at ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          mkdir -p ./artifact
          cp -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/* ./artifact/
          cd ./artifact
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p ./func-embedding-generator
          unzip release.zip -d ./func-embedding-generator/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A376817DC7E543B88345B9FA03A1F910 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0ED8AC039B94C16B32F7AEF7934CD8A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5342D9E3A76A467494BFCAA3EA0B1050 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-embedding-generator'
          slot-name: 'Production'
          package: './func-embedding-generator'