name: Build and deploy Python project to Azure Function App - func-profile-generator

on:
  push:
    branches:
      - main
    paths:
      - 'profile-generator/**'
      - '.github/workflows/main_func-profile-generator.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './profile-generator' # Chemin vers le dossier de la fonction profile-generator
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./profile-generator
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_94840406DA334DC382FF279AF9F3ABBB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_581C045B73964BEFA16ADFDCFBEF99DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4ADDA1932EAE4B95B04122381A96F4F6 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-profile-generator'
          slot-name: 'Production'
          package: './profile-generator'

# Ajout d'un filtre paths pour déclencher le workflow uniquement lors de modifications dans le dossier profile-generator
# Changement du chemin dans AZURE_FUNCTIONAPP_PACKAGE_PATH pour pointer vers ./profile-generator
# Modification des commandes d'installation des dépendances pour cibler le dossier de la fonction
# Adaptation du processus de zip/unzip pour traiter correctement les fichiers du dossier profile-generator
# Mise à jour du chemin de déploiement final vers ./profile-generator