name: Deploy Profile Updater Function

on:
  push:
    branches: [ "main" ]
    paths:
      - 'functions/func-profile-updater/**'  # Ajout du path spécifique
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions/func-profile-updater'  # Chemin corrigé
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  # Se déplacer dans le bon dossier
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  # Se déplacer dans le bon dossier
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC08EDF67DBD4717A2FE17C14B3369DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B41D128708E4C5186846CE68480116F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_59CD19CA468B473281380A4D79249BF5 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-profile-updater'
          slot-name: 'Production'
          package: '.'